sudo: false
language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
  - "pypy3"
# test command
script: python setup.py install && python setup.py test && cmark.py README.md && cmark.py README.md -a && cmark.py README.md -aj
